### ISSUE TITLE
Unable to download image

### ISSUE THREAD

**Issue by rkumar0am** [DevHyperCoder/ImageDownloader#1]
Whatever be the querycontent , 

Getting below errors 
Unfortunately all 5 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

**Comment by DevHyperCoder** [comment]
Please try adding a print statement in the except block to catch the exception and please post the stack trace here 🙂

**Comment by rkumar0am** [comment]
Please find the snippet


Unfortunately all 5 could not be downloaded because some images were not downloadable. 0 is all we got for this search filter!

Errors: 0

({'DOG': []}, 0)

**Comment by rkumar0am** [comment]
While debugging noticed, the issue happening in below snippet
![image](https://user-images.githubusercontent.com/31585211/92327420-540af480-f077-11ea-8291-6113d8738d68.png)

And, the URL framed for the query string "DOG" is
https://www.google.com/search?q=DOG&espv=2&biw=1366&bih=667&site=webhp&source=lnms&tbm=isch&tbs=isz:m,iar:xw,ift:jpg&sa=X&ei=XosDVaCXD8TasATItgE&ved=0CAcQ_AUoAg

**Comment by DevHyperCoder** [comment]
mostly it is a library issue i think. probably you could open a issue in the link : https://github.com/hardikvasa/google-images-download/issues
